- added check for isolinux-config in suse-isolinux - added checks for copy calls in KIWIImage.pm while creating   a live ISO image
git-svn-id: https://svn.berlios.de/svnroot/repos/kiwi/kiwi-head@632 92bc7f66-5d17-0410-ac0d-e081219a1bb3

diff --git a/system/boot/isoboot/suse-isolinux b/system/boot/isoboot/suse-isolinux
--- a/system/boot/isoboot/suse-isolinux
+++ b/system/boot/isoboot/suse-isolinux
@@ -198,7 +198,12 @@ then
 	fi
 fi
 
-/usr/bin/isolinux-config --base $BOOT_ISOLINUX $SOURCE/$BOOT_ISOLINUX/isolinux.bin
+if [ ! -x /usr/bin/isolinux-config ];then
+	echo "Can't find isolinux-config binary"
+	exit 1
+fi
+/usr/bin/isolinux-config \
+	--base $BOOT_ISOLINUX $SOURCE/$BOOT_ISOLINUX/isolinux.bin
 mkisofs \
 	-p "$CD_PREPARER" \
 	-publisher "$CD_PUBLISHER" \
