- reverted isoboot patch....
git-svn-id: https://svn.berlios.de/svnroot/repos/kiwi/kiwi-head@704 92bc7f66-5d17-0410-ac0d-e081219a1bb3

diff --git a/system/boot/isoboot/suse-linuxrc b/system/boot/isoboot/suse-linuxrc
--- a/system/boot/isoboot/suse-linuxrc
+++ b/system/boot/isoboot/suse-linuxrc
@@ -99,17 +99,36 @@ IFS="," ; for i in $IMAGE;do
 	if [ ! -z "$UNIONFS_CONFIG" ];then
 		continue
 	fi
-	Echo "Loading $imageName [$imageDevice]..."
-	IFS=" "
-	read sum1 blocks blocksize < $imageMD5s
-	if ! validateSize;then
-		systemException \
-			"Not enough RAM available for this image" \
-		"reboot"
-	fi
-	gzip -cd $gzippName | \
-		dd of=$imageDevice count=$blocks bs=$blocksize \
-	>/dev/null 2>&1
+	while true;do
+		Echo "Loading $imageName [$imageDevice]..."
+		IFS=" "
+		read sum1 blocks blocksize < $imageMD5s
+		if ! validateSize;then
+			systemException \
+				"Not enough RAM available for this image" \
+			"reboot"
+		fi
+		gzip -cd $gzippName | dd of=$imageDevice count=$blocks \
+			bs=$blocksize >/dev/null 2>&1
+		dd if=$imageDevice count=$blocks bs=$blocksize 2>/dev/null |\
+			md5sum - > /etc/ireal.md5
+		read sum2 dumy < /etc/ireal.md5
+		if test $sum1 = $sum2;then
+			Echo "Image checksum test: fine :-)"
+			break
+		fi
+		Echo "Image checksum test failed:"
+		echo
+		Echo -b "1) Data corruption while loading the image:"
+		Echo -b "   will give it a new try..."
+		echo
+		Echo -b "2) ramdisk size is too small for the image:"
+		Echo -b "   try to set the kernel parameter ramdisk_size=<size>"
+		echo
+		Echo "Retry to load image..."
+		sleep 15
+	done
+	rm -f /etc/ireal.md5
 done
 CDUmount
 
