- some changes to the arm suse-13.2-JeOS template and code   * currently suse-13.2-JeOS contains only a profile for raspberry   * the vboot support uses no gpt if the berryboot loader is set   * vboot + berryboot creates a boot setup which let the standard     raspberry loader chainload our uboot which then loads the     kernel and initrd from a linux ext2 second partition

diff --git a/template/armv7l/suse-13.2-JeOS/berryboot-image-setup b/template/armv7l/suse-13.2-JeOS/berryboot-image-setup
--- a/template/armv7l/suse-13.2-JeOS/berryboot-image-setup
+++ b/template/armv7l/suse-13.2-JeOS/berryboot-image-setup
@@ -5,10 +5,31 @@ set -x
 # Set variables
 #------------------------------------------
 bootfs=$1
-file=boot/config.txt
+boot_cnf=boot/config.txt
+boot_scr=boot/boot.script
+boot_bin=boot/boot.scr
 
 #==========================================
-# Check for berryboot config.txt
+# Update uboot boot script
 #------------------------------------------
-echo 'disable_overscan=1' >> $file
+echo 'printenv kerneladdr || setenv kerneladdr ${kernel_addr_r}'   >> $boot_scr
+echo 'printenv ramdiskaddr|| setenv ramdiskaddr ${ramdisk_addr_r}' >> $boot_scr
+echo -n 'setenv bootcmd "'                                         >> $boot_scr
+if [[ $bootfs =~ fat ]];then
+	echo -n 'fatload mmc 0:1 ${kerneladdr} boot/linux.vmx; '      >> $boot_scr
+	echo -n 'fatload mmc 0:1 ${ramdiskaddr} boot/initrd.uboot; '  >> $boot_scr
+else
+	echo -n 'ext2load mmc 0:1 ${kerneladdr} boot/linux.vmx; '      >> $boot_scr
+	echo -n 'ext2load mmc 0:1 ${ramdiskaddr} boot/initrd.uboot; '  >> $boot_scr
+fi
+echo 'bootm ${kerneladdr} ${ramdiskaddr}";'                        >> $boot_scr
+echo 'boot' >> $boot_scr
 
+#==========================================
+# Create machine readable uboot format
+#------------------------------------------
+mkopts="-A arm -O linux -a 0 -e 0 -T script -C none";
+if ! mkimage $mkopts -n 'Boot-Script' -d $boot_scr $boot_bin;then
+	echo "Failed to create uboot script image"
+	exit 1
+fi
