Added restore of btrfs subvolumes in restore mode (bnc #908011)
In oem recovery (restore) mode a new function named
restoreBtrfsSubVolumes will be called if the root filesystem
is btrfs based. The function will restore the configured
subvolumes back to the factory state

diff --git a/system/boot/ppc/oemboot/suse-linuxrc b/system/boot/ppc/oemboot/suse-linuxrc
--- a/system/boot/ppc/oemboot/suse-linuxrc
+++ b/system/boot/ppc/oemboot/suse-linuxrc
@@ -372,6 +372,7 @@ if [ ! -z "$KIWI_RECOVERY" ];then
         fi
         umount $imageRecoveryDevice
         blockdev --rereadpt $imageDiskDevice
+        updateProtectiveMBR
         waitForStorageDevice $imageRecoveryDevice
         if ! mount -o ro $imageRecoveryDevice /reco-save >/dev/null;then
             systemException "Failed to remount recovery device" "reboot"
@@ -399,6 +400,12 @@ if [ ! -z "$KIWI_RECOVERY" ];then
             if ! mountSystem $imageRootDevice;then
                 Echo "Failed to mount root filesystem"
                 exit 1
+            fi
+            if [ "$FSTYPE" = "btrfs" ];then
+                if ! restoreBtrfsSubVolumes /mnt;then
+                    Echo "Failed to restore btrfs subvolumes"
+                    exit 1
+                fi
             fi
             for i in dev sys proc;do
                 mkdir -p /mnt/$i
diff --git a/system/boot/s390/oemboot/suse-linuxrc b/system/boot/s390/oemboot/suse-linuxrc
--- a/system/boot/s390/oemboot/suse-linuxrc
+++ b/system/boot/s390/oemboot/suse-linuxrc
@@ -404,6 +404,12 @@ if [ ! -z "$KIWI_RECOVERY" ];then
                 Echo "Failed to mount root filesystem"
                 exit 1
             fi
+            if [ "$FSTYPE" = "btrfs" ];then
+                if ! restoreBtrfsSubVolumes /mnt;then
+                    Echo "Failed to restore btrfs subvolumes"
+                    exit 1
+                fi
+            fi
             for i in dev sys proc;do
                 mkdir -p /mnt/$i
             done
