- fixed nbd port and swap setup (bnc #371554)
git-svn-id: https://svn.berlios.de/svnroot/repos/kiwi/kiwi-head@1118 92bc7f66-5d17-0410-ac0d-e081219a1bb3

diff --git a/system/boot/netboot/suse-linuxrc b/system/boot/netboot/suse-linuxrc
--- a/system/boot/netboot/suse-linuxrc
+++ b/system/boot/netboot/suse-linuxrc
@@ -494,7 +494,10 @@ else
 			nbdDevice="/dev/nbd0"
 		fi
 		if [ -z "$nbdswapDevice" ];then
-			nbdDevice="/dev/nbd1"
+			nbdswapDevice="/dev/nbd1"
+		fi
+		if [ -z "$nbdPort" ];then
+			nbdPort="2000"
 		fi
 		if [ -z "$nbdswapPort" ];then
 			nbdswapPort="9210"
@@ -503,25 +506,29 @@ else
 		if [ ! -b $nbdDevice ];then
 			systemException "Device $nbdDevice doesn't appear" "reboot"
 		fi
-		Echo "Mounting NBD root system: $nbdServer $nbdPort [$nbdDevice]..."
-		if ! /usr/sbin/nbd-client $nbdServer $nbdPort $nbdDevice;then
-			systemException "Failed to setup $nbdDevice device" "reboot"
-		fi
 		# /.../
 		# try to get swap from the server if we dont have
-		# enough ram (less than 48M)
+		# enough ram (less than 62MB)
 		# ----
-		min_ram=49152
+		min_ram=63488
 		real_ram=$(cat /proc/meminfo |grep MemTotal|tr -d " [a-z][A-Z]:")
 		if [ ${real_ram} -lt ${min_ram} ];then
-			Echo "NBD: memory is below required 48M"
-			Echo "NBD: Mounting NBD swap: $nbdServer $nbdPort [$nbdDevice]..."
+			Echo "NBD: memory is below required 62M"
+			Echo "NBD: Mounting swap: $nbdServer $nbdswapPort [$nbdswapDevice]"
+			if [ ! -b $nbdswapDevice ];then
+				systemException "Device $nbdswapDevice doesn't appear" "reboot"
+			fi
 			if ! /usr/sbin/nbd-client $nbdServer $nbdswapPort $nbdswapDevice
 			then
 				systemException "Failed to setup $nbdswapDevice device" "reboot"
 			fi
-			/sbin/mkswap $nbdswapDevice || true
+			Echo "NBD: Waiting for server to create swap space..."
+			sleep 3
 			/sbin/swapon $nbdswapDevice || true
+		fi
+		Echo "Mounting NBD root system: $nbdServer $nbdPort [$nbdDevice]..."
+		if ! /usr/sbin/nbd-client $nbdServer $nbdPort $nbdDevice;then
+			systemException "Failed to setup $nbdDevice device" "reboot"
 		fi
 		imageRootDevice=$nbdDevice
 		probeFileSystem $imageRootDevice
