- added nfs root support to kiwi's netboot image - added --logfile terminal option which causes all data from kiwi   and its screen sessions to be logged on the calling terminal
git-svn-id: https://svn.berlios.de/svnroot/repos/kiwi/kiwi-head@306 92bc7f66-5d17-0410-ac0d-e081219a1bb3

diff --git a/system/boot/netboot/suse-linuxrc b/system/boot/netboot/suse-linuxrc
--- a/system/boot/netboot/suse-linuxrc
+++ b/system/boot/netboot/suse-linuxrc
@@ -218,7 +218,7 @@ export systemIntegrity="unknown"
 # 9) Is this a diskful station
 #--------------------------------------
 if [ $LOCAL_BOOT = "no" ];then
-if [ ! -z $PART ];then
+if [ ! -z "$PART" ] && [ -z "$NFSROOT" ];then
 	#======================================
 	# Check for installed system
 	#--------------------------------------
@@ -276,174 +276,190 @@ fi
 #======================================
 # 10) Download network client image
 #--------------------------------------
-count=0
-IFS="," ; for i in $IMAGE;do
-	imageZipped="uncompressed"
-	count=$(($count + 1))
-	field=0
-	IFS=";" ; for n in $i;do
-	case $field in
-		0) imageDevice=$n ; field=1 ;;
-		1) imageName=$n   ; field=2 ;;
-		2) imageVersion=$n; field=3 ;;
-		3) imageServer=$n ; field=4 ;;
-		4) imageBlkSize=$n; field=5 ;;
-		5) imageZipped=$n ;
-	esac
-	done
-	if [ $count = 1 ];then
-		imageRootDevice=$imageDevice
-		imageRootName=$imageName
-	fi
-	if [ $count = 2 ];then
-		imageNextRootDevice=$imageDevice
-	fi
-	if [ $LOCAL_BOOT = "yes" ];then
-		continue
-	fi
-	if test `getSystemIntegrity $count` = "fine";then
-		continue
-	fi
-	imageName="image/$imageName-$imageVersion"
-	imageMD5s="$imageName.md5"
-	[ -z "$imageServer" ]  && imageServer=$TSERVER
-	[ -z "$imageBlkSize" ] && imageBlkSize=8192
-	while true;do
-		# /.../
-		# get image md5sum to be able to check for the size
-		# requirements if we are loading into RAM
-		# ---
-		loadStatus=`atftp -g \
-			-r $imageMD5s -l /etc/image.md5 $imageServer 2>&1`
-		if ! loadOK "$loadStatus";then
-			systemException \
-			"Failed to load image MD5: $imageName -> no such image MD5" \
-			"reboot"
+if [ -z "$NFSROOT" ];then
+	count=0
+	IFS="," ; for i in $IMAGE;do
+		imageZipped="uncompressed"
+		count=$(($count + 1))
+		field=0
+		IFS=";" ; for n in $i;do
+		case $field in
+			0) imageDevice=$n ; field=1 ;;
+			1) imageName=$n   ; field=2 ;;
+			2) imageVersion=$n; field=3 ;;
+			3) imageServer=$n ; field=4 ;;
+			4) imageBlkSize=$n; field=5 ;;
+			5) imageZipped=$n ;
+		esac
+		done
+		if [ $count = 1 ];then
+			imageRootDevice=$imageDevice
+			imageRootName=$imageName
 		fi
-		IFS=" "
-		read sum1 blocks blocksize < /etc/image.md5
-		if test -z $DISK;then
-			if ! validateRAM;then
+		if [ $count = 2 ];then
+			imageNextRootDevice=$imageDevice
+		fi
+		if [ $LOCAL_BOOT = "yes" ];then
+			continue
+		fi
+		if test `getSystemIntegrity $count` = "fine";then
+			continue
+		fi
+		imageName="image/$imageName-$imageVersion"
+		imageMD5s="$imageName.md5"
+		[ -z "$imageServer" ]  && imageServer=$TSERVER
+		[ -z "$imageBlkSize" ] && imageBlkSize=8192
+		while true;do
+			# /.../
+			# get image md5sum to be able to check for the size
+			# requirements if we are loading into RAM
+			# ---
+			loadStatus=`atftp -g \
+				-r $imageMD5s -l /etc/image.md5 $imageServer 2>&1`
+			if ! loadOK "$loadStatus";then
 				systemException \
-					"Not enough RAM available for this image" \
+				"Failed to load image MD5: $imageName -> no such image MD5" \
 				"reboot"
 			fi
-		else
-			if ! validateSize;then
+			IFS=" "
+			read sum1 blocks blocksize < /etc/image.md5
+			if test -z $DISK;then
+				if ! validateRAM;then
+					systemException \
+						"Not enough RAM available for this image" \
+					"reboot"
+				fi
+			else
+				if ! validateSize;then
+					systemException \
+						"Not enough space available for this image" \
+					"reboot"
+				fi
+			fi
+			validateBlockSize
+			# /.../
+			# now load the image into the imageDevice
+			# ---
+			multicast="-m"
+			if test "$imageZipped" = "compressed"; then
+				Echo "Compressed image found: Disable multicast download"
+				multicast=""
+				test ! -p /dev/compressed_image && mkfifo /dev/compressed_image
+				cat /dev/compressed_image | gzip -d > $imageDevice 2>/dev/null &
+				imageDevice_orig=$imageDevice
+				imageName_orig=$imageName
+				imageDevice="/dev/compressed_image"
+				imageName="$imageName.gz"
+			fi
+			Echo "Loading $imageName [$imageDevice BS:$imageBlkSize Byte]..."
+			loadStatus=`atftp $multicast --option "blksize $imageBlkSize" -g \
+				-r $imageName -l $imageDevice $imageServer 2>&1`
+			if ! loadOK "$loadStatus";then
 				systemException \
-					"Not enough space available for this image" \
+					"Failed to load image: $imageName -> no such image" \
 				"reboot"
 			fi
+			if test "$imageZipped" = "compressed"; then
+				imageDevice=$imageDevice_orig
+				imageName=$imageName_orig
+			fi
+			# /.../
+			# check the md5sum of the downloaded data records
+			# ----
+			Echo "Download complete, checking data..."
+			dd if=$imageDevice count=$blocks bs=$blocksize 2>/dev/null |\
+				md5sum - > /etc/ireal.md5
+			read sum2 dumy < /etc/ireal.md5
+			if test $sum1 = $sum2;then
+				Echo "Image checksum test: fine :-)"
+				break
+			fi
+			Echo "Image checksum test failed:"
+			Echo "Possible reasons:"
+			echo 
+			Echo -b "1) Physical ethernet connection lost:"
+			Echo -b "   please check cable"
+			echo
+			Echo -b "2) Data corruption while loading the image:"
+			Echo -b "   will give it a new try..."
+			echo
+			Echo -b "3) wrong checksum file created for the image:"
+			Echo -b "   check with the md5sum command if the image on the"
+			Echo -b "   TFTP server provides the same md5 sum as included"
+			Echo -b "   within the appropriate .md5 file for this image"
+			echo
+			if test -z $DISK;then
+			Echo -b "4) ramdisk size is too small for the image:"
+			Echo -b "   check the ramdisk_size parameter of the PXE"
+			Echo -b "   configuration file on the TFTP server"
+			else
+			Echo -b "4) partition size is too small for the image:"
+			Echo -b "   check the PART line in the image config file on the"
+			Echo -b "   TFTP server"
+			fi
+			echo
+			Echo "Retry to load image..."
+			sleep 15
+		done
+		echo $imageDevice | grep -q ram
+		haveDataInRam=$?
+		if test ! -z $DISK && test $haveDataInRam != 0;then
+			mountSystem $imageRootDevice
+			readFileSystem /mnt/image/config.xml
+			umountSystem
+			if test "$FSTYPE" = "reiserfs";then
+				Echo "Resize Reiser filesystem to full partition space..."
+				resize_reiserfs $imageDevice
+				INITRD_MODULES="$INITRD_MODULES reiserfs"
+			fi
+			if test "$FSTYPE" = "ext2";then
+				Echo "Checking EXT2 filesystem..."
+				e2fsck -f $imageDevice -y
+				Echo "Resize EXT2 filesystem to full partition space..."
+				resize2fs -F -p $imageDevice
+				Echo "Checking EXT2 filesystem..."
+				e2fsck -f $imageDevice -y
+				INITRD_MODULES="$INITRD_MODULES ext2"
+			fi
+			if test "$FSTYPE" = "ext3";then
+				Echo "Checking EXT3 filesystem..."
+				e2fsck -f $imageDevice -y
+				Echo "Resize EXT3 filesystem to full partition space..."
+				resize2fs -F -p $imageDevice
+				Echo "Adding EXT3 journal..."
+				tune2fs -j $imageDevice
+				Echo "Checking EXT3 filesystem..."
+				e2fsck -f $imageDevice -y
+				INITRD_MODULES="$INITRD_MODULES ext3"
+			fi
 		fi
-		validateBlockSize
-		# /.../
-		# now load the image into the imageDevice
-		# ---
-		multicast="-m"
-		if test "$imageZipped" = "compressed"; then
-			Echo "Compressed image found: Disable multicast download"
-			multicast=""
-			test ! -p /dev/compressed_image && mkfifo /dev/compressed_image
-			cat /dev/compressed_image | gzip -d > $imageDevice 2>/dev/null &
-			imageDevice_orig=$imageDevice
-			imageName_orig=$imageName
-			imageDevice="/dev/compressed_image"
-			imageName="$imageName.gz"
+		if test ! -z $DISK && test $haveDataInRam = 0;then
+			Echo "Including RAM device data to disk..."
+			RELOAD_CONFIG="yes"
+			mkdir -p /config
+			mountSystem
+			rm -rf /mnt/lost+found
+			cp -a /mnt/* /config && rm -f /mnt/*
+			umountSystem
 		fi
-		Echo "Loading $imageName [$imageDevice BS:$imageBlkSize Byte]..."
-		loadStatus=`atftp $multicast --option "blksize $imageBlkSize" -g \
-			-r $imageName -l $imageDevice $imageServer 2>&1`
-		if ! loadOK "$loadStatus";then
-			systemException \
-				"Failed to load image: $imageName -> no such image" \
-			"reboot"
-		fi
-		if test "$imageZipped" = "compressed"; then
-			imageDevice=$imageDevice_orig
-			imageName=$imageName_orig
-		fi
-		# /.../
-		# check the md5sum of the downloaded data records
-		# ----
-		Echo "Download complete, checking data..."
-		dd if=$imageDevice count=$blocks bs=$blocksize 2>/dev/null |\
-			md5sum - > /etc/ireal.md5
-		read sum2 dumy < /etc/ireal.md5
-		if test $sum1 = $sum2;then
-			Echo "Image checksum test: fine :-)"
-			break
-		fi
-		Echo "Image checksum test failed:"
-		Echo "Possible reasons:"
-		echo 
-		Echo -b "1) Physical ethernet connection lost:"
-		Echo -b "   please check cable"
-		echo
-		Echo -b "2) Data corruption while loading the image:"
-		Echo -b "   will give it a new try..."
-		echo
-		Echo -b "3) wrong checksum file created for the image:"
-		Echo -b "   check with the md5sum command if the image on the"
-		Echo -b "   TFTP server provides the same md5 sum as included"
-		Echo -b "   within the appropriate .md5 file for this image"
-		echo
-		if test -z $DISK;then
-		Echo -b "4) ramdisk size is too small for the image:"
-		Echo -b "   check the ramdisk_size parameter of the PXE"
-		Echo -b "   configuration file on the TFTP server"
-		else
-		Echo -b "4) partition size is too small for the image:"
-		Echo -b "   check the PART line in the image config file on the"
-		Echo -b "   TFTP server"
-		fi
-		echo
-		Echo "Retry to load image..."
-		sleep 15
+		rm -f /etc/ireal.md5
+		rm -f /etc/image.md5
 	done
-	echo $imageDevice | grep -q ram
-	haveDataInRam=$?
-	if test ! -z $DISK && test $haveDataInRam != 0;then
-		mountSystem $imageRootDevice
-		readFileSystem /mnt/image/config.xml
-		umountSystem
-		if test "$FSTYPE" = "reiserfs";then
-			Echo "Resize Reiser filesystem to full partition space..."
-			resize_reiserfs $imageDevice
-			INITRD_MODULES="$INITRD_MODULES reiserfs"
-		fi
-		if test "$FSTYPE" = "ext2";then
-			Echo "Checking EXT2 filesystem..."
-			e2fsck -f $imageDevice -y
-			Echo "Resize EXT2 filesystem to full partition space..."
-			resize2fs -F -p $imageDevice
-			Echo "Checking EXT2 filesystem..."
-			e2fsck -f $imageDevice -y
-			INITRD_MODULES="$INITRD_MODULES ext2"
-		fi
-		if test "$FSTYPE" = "ext3";then
-			Echo "Checking EXT3 filesystem..."
-			e2fsck -f $imageDevice -y
-			Echo "Resize EXT3 filesystem to full partition space..."
-			resize2fs -F -p $imageDevice
-			Echo "Adding EXT3 journal..."
-			tune2fs -j $imageDevice
-			Echo "Checking EXT3 filesystem..."
-			e2fsck -f $imageDevice -y
-			INITRD_MODULES="$INITRD_MODULES ext3"
-		fi
-	fi
-	if test ! -z $DISK && test $haveDataInRam = 0;then
-		Echo "Including RAM device data to disk..."
-		RELOAD_CONFIG="yes"
-		mkdir -p /config
-		mountSystem
-		rm -rf /mnt/lost+found
-		cp -a /mnt/* /config && rm -f /mnt/*
-		umountSystem
-	fi
-	rm -f /etc/ireal.md5
-	rm -f /etc/image.md5
-done
+else
+	IFS="," ; for i in $NFSROOT;do
+		field=0
+		IFS=";" ; for n in $i;do
+		case $field in
+			0) nfsRootServer=$n ; field=1 ;;
+			1) nfsRootDevice=$n ; field=2
+		esac
+		done
+		Echo "Mounting NFS root system: $nfsRootServer:$nfsRootDevice..."
+		imageRootDevice="-o rw $nfsRootServer:$nfsRootDevice"
+		imageRootName="NFSRoot-System"
+		systemIntegrity="clean"
+	done
+fi
 
 #======================================
 # 11) Check for RELOAD_CONFIG
@@ -515,7 +531,7 @@ fi
 #======================================
 # 14) send DHCP_RELEASE, reset cache
 #--------------------------------------
-if [ $LOCAL_BOOT = "no" ];then
+if [ $LOCAL_BOOT = "no" ] && [ -z "$NFSROOT" ];then
 	if test $systemIntegrity = "clean";then
 		dhcpcd -k
 	fi
@@ -524,7 +540,7 @@ fi
 #======================================
 # 15) Check if this is a split image
 #--------------------------------------
-if test ! -z $COMBINED_IMAGE; then
+if [ ! -z "$COMBINED_IMAGE" ] && [ -z "$NFSROOT" ]; then
 	READ_ONLY_SYSTEM=system
 	mkdir -p /mnt/$READ_ONLY_SYSTEM && \
 		mount $imageNextRootDevice /mnt/$READ_ONLY_SYSTEM
@@ -546,7 +562,7 @@ if [ $LOCAL_BOOT = "no" ];then
 fi
 
 #======================================
-# 17) make kernel/initrd available on unionfs
+# 17) make initrd available on unionfs
 #--------------------------------------
 if [ $LOCAL_BOOT = "no" ];then
 	if test ! -z "$UNIONFS_CONFIG" && test $systemIntegrity = "clean";then
