- Update indention level to 4 spaces

diff --git a/doc/examples/extras/suse-12.3/suse-nebula-cloud/cloud_guest/root/etc/init.d/boot b/doc/examples/extras/suse-12.3/suse-nebula-cloud/cloud_guest/root/etc/init.d/boot
--- a/doc/examples/extras/suse-12.3/suse-nebula-cloud/cloud_guest/root/etc/init.d/boot
+++ b/doc/examples/extras/suse-12.3/suse-nebula-cloud/cloud_guest/root/etc/init.d/boot
@@ -26,7 +26,7 @@ set +e
 #
 test -z "$CONSOLE" && CONSOLE=/dev/console
 set -- $(stty size < $CONSOLE)
-  LINES=$1
+    LINES=$1
 COLUMNS=$2
 export LINES COLUMNS CONSOLE
 
@@ -41,10 +41,10 @@ exec 0<> $CONSOLE 1>&0 2>&0
 REDIRECT="`showconsole 2>/dev/null`"
 export REDIRECT
 if test $COLUMNS -eq 0 ; then
-    # Serial: columns and lines are not defined
-      LINES=24
-    COLUMNS=80
-    test "$TERM" = "linux" -o -z "$TERM" && TERM=vt102
+        # Serial: columns and lines are not defined
+            LINES=24
+        COLUMNS=80
+        test "$TERM" = "linux" -o -z "$TERM" && TERM=vt102
 fi
 
 #
@@ -70,27 +70,27 @@ mount -n -t sysfs sysfs /sys
 rc_status -v -r
 
 if test -d /sys/kernel/debug ; then
-    while read dev type ; do
-  if test "$type" = "debugfs" ; then
-      echo -n "Mounting debugfs at /sys/kernel/debug"
-      mount -n -t debugfs debugfs /sys/kernel/debug
-      rc_status -v -r
-  fi
-    done < /proc/filesystems
+        while read dev type ; do
+    if test "$type" = "debugfs" ; then
+            echo -n "Mounting debugfs at /sys/kernel/debug"
+            mount -n -t debugfs debugfs /sys/kernel/debug
+            rc_status -v -r
+    fi
+        done < /proc/filesystems
 fi
 #
 # mount tmpfs on /dev if not already done by initramfs
 #
 while read dev dir type options; do
-    if test "$dir" = "/dev" -a "$type" = "tmpfs"; then
-  DEV_MOUNTED=1;
-  break;
-    fi
+        if test "$dir" = "/dev" -a "$type" = "tmpfs"; then
+    DEV_MOUNTED=1;
+    break;
+        fi
 done < /proc/mounts
 if test -z "$DEV_MOUNTED"; then
-    echo -n "Mounting tmpfs at /dev"
-    mount -n -t tmpfs -o mode=0755 udev /dev
-    rc_status -v -r
+        echo -n "Mounting tmpfs at /dev"
+        mount -n -t tmpfs -o mode=0755 udev /dev
+        rc_status -v -r
 fi
 
 #
@@ -111,9 +111,9 @@ rc_status -v -r
 #
 otty=$(stty -g)
 if test "$FLOW_CONTROL" = "yes" ; then
-    stty -nl  ixon ignbrk -brkint
+        stty -nl  ixon ignbrk -brkint
 else
-    stty -nl -ixon ignbrk -brkint
+        stty -nl -ixon ignbrk -brkint
 fi
 
 #
@@ -122,21 +122,21 @@ fi
 DO_CONFIRM=""
 read -t 2 check < /proc/cmdline 2> /dev/null
 case "$check" in
-    *confirm*) DO_CONFIRM=yes ;;
+        *confirm*) DO_CONFIRM=yes ;;
 esac
 test -z "$CONFIRM_PROMPT_TIMEOUT" && CONFIRM_PROMPT_TIMEOUT=5
 if test "$PROMPT_FOR_CONFIRM" = "yes" -a "$DO_CONFIRM" != "yes" ; then
-    echo -en "${extd}Enter Interactive startup mode?${norm}"
-    rc_timer_on "$CONFIRM_PROMPT_TIMEOUT" 37
-    read -t "$CONFIRM_PROMPT_TIMEOUT" -n 1 \
-  -p " ${extd}y${norm}/[${extd}n${norm}]("${CONFIRM_PROMPT_TIMEOUT}s") " answer
-    rc_timer_off
-    case "$answer" in
-    [yYiI]) DO_CONFIRM=yes ;;
-    *)      DO_CONFIRM=    ;;
-    esac
-    unset answer
-    echo
+        echo -en "${extd}Enter Interactive startup mode?${norm}"
+        rc_timer_on "$CONFIRM_PROMPT_TIMEOUT" 37
+        read -t "$CONFIRM_PROMPT_TIMEOUT" -n 1 \
+    -p " ${extd}y${norm}/[${extd}n${norm}]("${CONFIRM_PROMPT_TIMEOUT}s") " answer
+        rc_timer_off
+        case "$answer" in
+        [yYiI]) DO_CONFIRM=yes ;;
+        *)      DO_CONFIRM=    ;;
+        esac
+        unset answer
+        echo
 fi
 export DO_CONFIRM
 
@@ -146,11 +146,11 @@ export DO_CONFIRM
 #
 test -x /sbin/blogd -a -n "$REDIRECT" && /sbin/blogd $REDIRECT
 if test -z "$REDIRECT" ; then
-    if (echo -n > /dev/tty) 2>/dev/null ; then
-  REDIRECT=/dev/tty
-    else
-  REDIRECT=/dev/console
-    fi
+        if (echo -n > /dev/tty) 2>/dev/null ; then
+    REDIRECT=/dev/tty
+        else
+    REDIRECT=/dev/console
+        fi
 fi
 
 #
@@ -182,60 +182,60 @@ startpar -v &> /dev/null   || RUN_PARALLEL="no"
 #
 if test "$RUN_PARALLEL" = "yes" ; then
 
-    #
-    # Start scripts in parallel with make behaviour of startpar
-    #
+        #
+        # Start scripts in parallel with make behaviour of startpar
+        #
 
-    startopt="-p4 -t 30 -T 3 $(splashmake)"
-    eval $(startpar $startopt -M boot)
-    failed="${failed:+$failed }$failed_service"
-    skipped="${skipped:+$skipped }$skipped_service"
+        startopt="-p4 -t 30 -T 3 $(splashmake)"
+        eval $(startpar $startopt -M boot)
+        failed="${failed:+$failed }$failed_service"
+        skipped="${skipped:+$skipped }$skipped_service"
 
-    unset failed_service skipped_service startopt
+        unset failed_service skipped_service startopt
 
 elif test -d ${bootrc}/ ; then
 
-    #
-    # Start scripts in given link order
-    #
-    for i in ${bootrc}/S${rex}*; do
+        #
+        # Start scripts in given link order
+        #
+        for i in ${bootrc}/S${rex}*; do
 
-  test -f $i || continue
+    test -f $i || continue
 
-  B=${i##*/}
-  script=${B#*S$rex}
-  B=${B%$script}
+    B=${i##*/}
+    script=${B#*S$rex}
+    B=${B%$script}
 
-  if test "$DO_CONFIRM" = "yes" ; then
-      rc_confirm -t $CONFIRM_PROMPT_TIMEOUT "Start bootup script ${script}" < $REDIRECT > $REDIRECT 2>&1
-      case "$?" in
-      0) true     ;;
-      1) continue ;;
-      2) DO_CONFIRM=""
-      esac
-  fi
+    if test "$DO_CONFIRM" = "yes" ; then
+            rc_confirm -t $CONFIRM_PROMPT_TIMEOUT "Start bootup script ${script}" < $REDIRECT > $REDIRECT 2>&1
+            case "$?" in
+            0) true     ;;
+            1) continue ;;
+            2) DO_CONFIRM=""
+            esac
+    fi
 
-  blogger "$script start"
+    blogger "$script start"
 
-  if test -x "$i" ; then
-    $i start
-  else
-      echo Running $i
-      /bin/sh $i b
-      rc_status -v1 -r
-  fi
-  status=$?
-  echo -en "$rc_reset"
-  splashprogress "$script start"
+    if test -x "$i" ; then
+        $i start
+    else
+            echo Running $i
+            /bin/sh $i b
+            rc_status -v1 -r
+    fi
+    status=$?
+    echo -en "$rc_reset"
+    splashprogress "$script start"
 
-  case $status in
-  [1-47])  failed="${failed:+$failed }$script"   ;;
-  [56])   skipped="${skipped:+$skipped }$script" ;;
-  0|*) ;;
-  esac
+    case $status in
+    [1-47])  failed="${failed:+$failed }$script"   ;;
+    [56])   skipped="${skipped:+$skipped }$script" ;;
+    0|*) ;;
+    esac
 
-  blogger "'$script start' exits with status $status"
-    done
+    blogger "'$script start' exits with status $status"
+        done
 fi
 
 splashtrigger "rlreached B"
@@ -246,27 +246,27 @@ splashtrigger "rlreached B"
 echo -n "System Boot Control: "
 echo -e "The system has been ${stat}${extd}set up${norm}"
 if test -n "$failed" ; then
-    n=$((${#failed} + 7))
-    echo -n  "Failed features: "
-    test $n -lt 47 && echo -en "\033[${COLUMNS}C\033[${n}D"
-    echo -e  "${warn}${failed}${norm}"
+        n=$((${#failed} + 7))
+        echo -n  "Failed features: "
+        test $n -lt 47 && echo -en "\033[${COLUMNS}C\033[${n}D"
+        echo -e  "${warn}${failed}${norm}"
 fi
 if test -n "$skipped" ; then
-    n=$((${#skipped} + 7))
-    echo -n  "Skipped features: "
-    test $n -lt 47 && echo -en "\033[${COLUMNS}C\033[${n}D"
-    echo -e  "${attn}${skipped}${norm}"
+        n=$((${#skipped} + 7))
+        echo -n  "Skipped features: "
+        test $n -lt 47 && echo -en "\033[${COLUMNS}C\033[${n}D"
+        echo -e  "${attn}${skipped}${norm}"
 fi
 
 #
 # Start user defined bootup script.
 #
 if test -f /etc/init.d/boot.local ; then
-    echo -n "System Boot Control: "
-    echo "Running /etc/init.d/boot.local"
-    /bin/sh /etc/init.d/boot.local
-    rc_status -v1 -r
-    splashtrigger "boot.local"
+        echo -n "System Boot Control: "
+        echo "Running /etc/init.d/boot.local"
+        /bin/sh /etc/init.d/boot.local
+        rc_status -v1 -r
+        splashtrigger "boot.local"
 fi
 
 #
@@ -283,7 +283,7 @@ test -s /lib/bootcycle/stats && . /lib/bootcycle/stats
 # Remember for master resource script
 #
 if test "$DO_CONFIRM" = "yes" ; then
-    touch /var/run/do_confirm
+        touch /var/run/do_confirm
 fi
 
 #
@@ -295,34 +295,34 @@ stty $otty
 # Let YaST2 finish its installation, if you installed with YaST2
 #
 if test -f /var/lib/YaST2/runme_at_boot ; then
-    HOSTTYPE=$(uname -m)
-    splashtrigger "YaST"
-    exec 0<> $REDIRECT 1>&0 2>&0
-    # if yast2 failed, this ensures proper system setup
-    #ulimit -c unlimited
-    touch /var/lib/YaST2/run_suseconfig
-    if test -x /usr/lib/YaST2/startup/YaST2.Second-Stage; then
-  /usr/lib/YaST2/startup/YaST2.Second-Stage
-    else
-  # oops, yast2 not installed
-  rm -f /var/lib/YaST2/runme_at_boot
-    fi
+        HOSTTYPE=$(uname -m)
+        splashtrigger "YaST"
+        exec 0<> $REDIRECT 1>&0 2>&0
+        # if yast2 failed, this ensures proper system setup
+        #ulimit -c unlimited
+        touch /var/lib/YaST2/run_suseconfig
+        if test -x /usr/lib/YaST2/startup/YaST2.Second-Stage; then
+    /usr/lib/YaST2/startup/YaST2.Second-Stage
+        else
+    # oops, yast2 not installed
+    rm -f /var/lib/YaST2/runme_at_boot
+        fi
 fi
 if test -f /var/lib/YaST2/reconfig_system ; then
-    HOSTTYPE=$(uname -m)
-    splashtrigger "YaST"
-    exec 0<> $REDIRECT 1>&0 2>&0
-    if test -x /usr/lib/YaST2/startup/YaST2.Firstboot; then
-  /usr/lib/YaST2/startup/YaST2.Firstboot
-    else
-  # oops, yast2-firstboot not installed
-  rm -f /var/lib/YaST2/reconfig_system
-    fi
+        HOSTTYPE=$(uname -m)
+        splashtrigger "YaST"
+        exec 0<> $REDIRECT 1>&0 2>&0
+        if test -x /usr/lib/YaST2/startup/YaST2.Firstboot; then
+    /usr/lib/YaST2/startup/YaST2.Firstboot
+        else
+    # oops, yast2-firstboot not installed
+    rm -f /var/lib/YaST2/reconfig_system
+        fi
 fi
 # run SuSEconfig (with args) if needed
 if test -f /var/lib/YaST2/run_suseconfig ; then
-    /sbin/SuSEconfig `cat /var/lib/YaST2/run_suseconfig`
-    rm -f /var/lib/YaST2/run_suseconfig
+        /sbin/SuSEconfig `cat /var/lib/YaST2/run_suseconfig`
+        rm -f /var/lib/YaST2/run_suseconfig
 fi
 
 rc_reset
diff --git a/template/armv7l/suse-13.1-JeOS/uboot-image-setup b/template/armv7l/suse-13.1-JeOS/uboot-image-setup
--- a/template/armv7l/suse-13.1-JeOS/uboot-image-setup
+++ b/template/armv7l/suse-13.1-JeOS/uboot-image-setup
@@ -11,9 +11,9 @@ file=boot/boot.script
 # Check for berryboot config.txt
 #------------------------------------------
 if [ -f "boot/config.txt" ];then
-  file=boot/config.txt
-  echo 'disable_overscan=1' >> $file
-  exit 0
+    file=boot/config.txt
+    echo 'disable_overscan=1' >> $file
+    exit 0
 fi
 
 #==========================================
@@ -23,11 +23,11 @@ echo 'printenv kerneladdr || setenv kerneladdr ${kernel_addr_r}'   >> $file
 echo 'printenv ramdiskaddr|| setenv ramdiskaddr ${ramdisk_addr_r}' >> $file
 echo -n 'setenv bootcmd "'                                         >> $file
 if [[ $bootfs =~ fat ]];then
-  echo -n 'fatload mmc 0:1 ${kerneladdr} boot/linux.vmx; '       >> $file
-  echo -n 'fatload mmc 0:1 ${ramdiskaddr} boot/initrd.uboot; '   >> $file
+    echo -n 'fatload mmc 0:1 ${kerneladdr} boot/linux.vmx; '       >> $file
+    echo -n 'fatload mmc 0:1 ${ramdiskaddr} boot/initrd.uboot; '   >> $file
 else
-  echo -n 'ext2load mmc 0:1 ${kerneladdr} boot/linux.vmx; '      >> $file
-  echo -n 'ext2load mmc 0:1 ${ramdiskaddr} boot/initrd.uboot; '  >> $file
+    echo -n 'ext2load mmc 0:1 ${kerneladdr} boot/linux.vmx; '      >> $file
+    echo -n 'ext2load mmc 0:1 ${ramdiskaddr} boot/initrd.uboot; '  >> $file
 fi
 echo 'bootm ${kerneladdr} ${ramdiskaddr}";'                        >> $file
 echo 'boot'                                                        >> $file
@@ -39,7 +39,7 @@ mkopts="-A arm -O linux -a 0 -e 0 -T script -C none";
 inputf="boot/boot.script";
 result="boot/boot.scr";
 if ! mkimage $mkopts -n 'Boot-Script' -d $inputf $result;then
-  echo "Failed to create uboot script image"
-  exit 1
+    echo "Failed to create uboot script image"
+    exit 1
 fi
 
diff --git a/tools/livestick/livestick b/tools/livestick/livestick
--- a/tools/livestick/livestick
+++ b/tools/livestick/livestick
@@ -18,8 +18,8 @@
 # pre-checks
 #------------------------------------------
 if [ -z "$1" ] || [ -z "$2" ];then
-  echo "Usage: livestick kiwi-live.iso /dev/stick"
-  exit 1
+    echo "Usage: livestick kiwi-live.iso /dev/stick"
+    exit 1
 fi
 
 #==========================================
@@ -31,11 +31,11 @@ fi
 # Functions
 #------------------------------------------
 function clean {
-  umount /mnt &>/dev/null
-  if [ -d "$tmpdir" ];then
-    rm -rf $tmpdir
-  fi
-  exit 1
+    umount /mnt &>/dev/null
+    if [ -d "$tmpdir" ];then
+        rm -rf $tmpdir
+    fi
+    exit 1
 }
 
 #==========================================
@@ -54,19 +54,19 @@ basetheme=upstream
 disk=$2
 signature=$(blkid $disk -s TYPE -o value 2>/dev/null)
 if [ ! -z "$signature" ] && [ ! "$signature" = "iso9660" ];then
-  echo "Found filesystem signature $signature on $disk"
-  echo "Need a stick disk device not a partition"
-  clean
+    echo "Found filesystem signature $signature on $disk"
+    echo "Need a stick disk device not a partition"
+    clean
 fi
 device_disk=$(getDiskID $disk)
 device_part=$(getDiskID $(ddn $(dn $device_disk) 1))
 if [ ! -e "$device_disk" ];then
-  echo "Can't find disk for $disk"
-  clean
+    echo "Can't find disk for $disk"
+    clean
 fi
 if [ ! -e "$device_part" ];then
-  echo "Can't find partition $device_part for $disk"
-  clean
+    echo "Can't find partition $device_part for $disk"
+    clean
 fi
 
 #==========================================
@@ -75,16 +75,16 @@ fi
 image=$1
 image_base=$(basename $image)
 if [ ! -e $image ];then
-  echo "Can't find OS image"
-  clean
+    echo "Can't find OS image"
+    clean
 fi
 #==========================================
 # check if file is a kiwi live iso
 #------------------------------------------
 if ! isoinfo -l -i $image 2>/dev/null | grep -q LIVEBOOT;then
-  echo "Can't find live iso signature"
-  echo "Make sure the given kiwi image file is of type: image=iso"
-  clean
+    echo "Can't find live iso signature"
+    echo "Make sure the given kiwi image file is of type: image=iso"
+    clean
 fi
 
 #==========================================
@@ -92,8 +92,8 @@ fi
 #------------------------------------------
 tmpdir=$(mktemp -q -d /tmp/kiwi-livestick.XXXXXX)
 if [ ! -d $tmpdir ];then
-  echo "Can't create tmpdir"
-  clean
+    echo "Can't create tmpdir"
+    clean
 fi
 mkdir -p $tmpdir/boot/grub2
 
@@ -103,8 +103,8 @@ mkdir -p $tmpdir/boot/grub2
 echo "==> Preparation in progress..."
 theme=/usr/share/kiwi/livestick/theme/$basetheme/booting.tgz
 if ! tar -C $tmpdir/boot/grub2 -xf $theme;then
-  echo "Can't extract grub2 theme files"
-  clean
+    echo "Can't extract grub2 theme files"
+    clean
 fi
 
 #==========================================
@@ -112,16 +112,16 @@ fi
 #------------------------------------------
 tools=/usr/share/kiwi/livestick/theme/$basetheme/tooling.tgz
 if ! tar -C $tmpdir/boot -xf $tools; then
-  echo "Can't extract boot helper files"
-  clean
+    echo "Can't extract boot helper files"
+    clean
 fi
 
 #==========================================
 # hard link grub2 stages
 #------------------------------------------
 if [ ! -d /boot/grub2/i386-pc ];then
-  echo "Can't find grub2(i386-pc) on this system"
-  clean
+    echo "Can't find grub2(i386-pc) on this system"
+    clean
 fi
 cp -a /boot/grub2/i386-pc $tmpdir/boot/grub2
 
@@ -144,10 +144,10 @@ echo 'set prefix=($root)/boot/grub2'   >> $conf
 conf=$tmpdir/boot/grub2/grub.cfg
 arch=x86_64
 if ! isoinfo -p -i $image | grep -q X86_64;then
-  arch=i386
-  title=$(echo $image_base | sed -e s@\.i.86.*@@)
+    arch=i386
+    title=$(echo $image_base | sed -e s@\.i.86.*@@)
 else
-  title=$(echo $image_base | sed -e s@\.x86_64.*@@)
+    title=$(echo $image_base | sed -e s@\.x86_64.*@@)
 fi
 cmdline_std="isofrom_device=$device_part"
 cmdline_std="$cmdline_std isofrom_system=/boot/$image_base"
@@ -165,46 +165,46 @@ search --no-floppy --fs-uuid --set=root $uuid
 set default=0
 set font=/boot/grub2/fonts/unicode.pf2
 if loadfont \$font ;then
-    set gfxmode=auto
-    insmod gfxterm
-    insmod gfxmenu
-    if terminal_output gfxterm; then true; else
-        terminal gfxterm
-    fi
+        set gfxmode=auto
+        insmod gfxterm
+        insmod gfxmenu
+        if terminal_output gfxterm; then true; else
+                terminal gfxterm
+        fi
 fi
 if loadfont /boot/grub2/themes/$basetheme/ascii.pf2;then
-    loadfont /boot/grub2/themes/$basetheme/DejaVuSans-Bold14.pf2
-    loadfont /boot/grub2/themes/$basetheme/DejaVuSans10.pf2
-    loadfont /boot/grub2/themes/$basetheme/DejaVuSans12.pf2
-    loadfont /boot/grub2/themes/$basetheme/ascii.pf2
-    set theme=/boot/grub2/themes/$basetheme/theme.txt
-    background_image -m stretch /boot/grub2/themes/$basetheme/background.png
+        loadfont /boot/grub2/themes/$basetheme/DejaVuSans-Bold14.pf2
+        loadfont /boot/grub2/themes/$basetheme/DejaVuSans10.pf2
+        loadfont /boot/grub2/themes/$basetheme/DejaVuSans12.pf2
+        loadfont /boot/grub2/themes/$basetheme/ascii.pf2
+        set theme=/boot/grub2/themes/$basetheme/theme.txt
+        background_image -m stretch /boot/grub2/themes/$basetheme/background.png
 fi
 set timeout=10
 menuentry "$title" --class os {
-  set gfxpayload=auto
-    echo Loading live system...
-    loopback loop /boot/$image_base
-  echo Loading linux...
-    linux (loop)/boot/$arch/loader/linux $cmdline_std quiet
-  echo Loading initrd...
-    initrd (loop)/boot/$arch/loader/initrd
+    set gfxpayload=auto
+        echo Loading live system...
+        loopback loop /boot/$image_base
+    echo Loading linux...
+        linux (loop)/boot/$arch/loader/linux $cmdline_std quiet
+    echo Loading initrd...
+        initrd (loop)/boot/$arch/loader/initrd
 }
 menuentry "Failsafe -- $title" --class os {
-  set gfxpayload=auto
-    echo Loading live system...
-    loopback loop /boot/$image_base
-    echo Loading linux...
-    linux (loop)/boot/$arch/loader/linux $cmdline_fsf quiet
-    echo Loading initrd...
-    initrd (loop)/boot/$arch/loader/initrd
+    set gfxpayload=auto
+        echo Loading live system...
+        loopback loop /boot/$image_base
+        echo Loading linux...
+        linux (loop)/boot/$arch/loader/linux $cmdline_fsf quiet
+        echo Loading initrd...
+        initrd (loop)/boot/$arch/loader/initrd
 }
 menuentry "Boot from Hard Disk" --class os {
-    set root=(hd1)
-    chainloader +1
+        set root=(hd1)
+        chainloader +1
 }
 menuentry "Memory Test" --class os {
-    linux16 /boot/memtest
+        linux16 /boot/memtest
 }
 EOF
 
@@ -212,8 +212,8 @@ EOF
 # hard link image
 #------------------------------------------
 if ! cp -l $image $tmpdir/boot;then
-  echo "Can't copy image"
-  clean
+    echo "Can't copy image"
+    clean
 fi
 
 #==========================================
@@ -227,16 +227,16 @@ biosmod="$biosmod multiboot search configfile fat ntfs"
 core=$tmpdir/boot/grub2/$format/core.img
 bootconf=$tmpdir/boot/grub2/bootpart.cfg
 if ! grub2-mkimage -O $format -o $core -c $bootconf $biosmod &>/dev/null;then
-  echo "Can't create core boot image"
-  clean
+    echo "Can't create core boot image"
+    clean
 fi
 
 #==========================================
 # create cow file space
 #------------------------------------------
 if ! qemu-img create $tmpdir/boot/cowfile 500M &>/dev/null;then
-  echo "Can't create cow file"
-  clean
+    echo "Can't create cow file"
+    clean
 fi
 
 #==========================================
@@ -244,17 +244,17 @@ fi
 #------------------------------------------
 echo "==> Mounting stick..."
 if ! mount $device_part /mnt;then
-  echo "Can't mount target device"
-  clean
+    echo "Can't mount target device"
+    clean
 fi
 
 #==========================================
 # sync tmpdir to / on the stick
 #------------------------------------------
 if ! rsync -rltvh --progress --modify-window=1 --delete $tmpdir/* /mnt;then
-  echo "Can't rsync data to target"
-  umount /mnt
-  clean
+    echo "Can't rsync data to target"
+    umount /mnt
+    clean
 fi
 
 #==========================================
@@ -263,14 +263,14 @@ fi
 stages=/mnt/boot/grub2/$format
 devmap=/mnt/boot/grub2/device.map
 if ! sfdisk $device_disk --force -A 1;then
-  echo "Can't set first partition active"
-  umount /mnt
-  clean
+    echo "Can't set first partition active"
+    umount /mnt
+    clean
 fi
 if ! grub2-bios-setup -f -d $stages -m $devmap $device_disk &>/dev/null;then
-  echo "Can't install grub2 into MBR"
-  umount /mnt
-  clean
+    echo "Can't install grub2 into MBR"
+    umount /mnt
+    clean
 fi
 
 echo "==> Umount..."
