- fixed buildhost image: added hosts, fixed bsworker - fixed kernel extracting, extract for boot images only
git-svn-id: https://svn.berlios.de/svnroot/repos/kiwi/kiwi-head@39 92bc7f66-5d17-0410-ac0d-e081219a1bb3

diff --git a/system/netboot-suse-10.1/root/linuxrc b/system/netboot-suse-10.1/root/linuxrc
--- a/system/netboot-suse-10.1/root/linuxrc
+++ b/system/netboot-suse-10.1/root/linuxrc
@@ -280,12 +280,17 @@ createFileSystem () {
 		pvcreate $diskPartition >/dev/null 2>&1
 		vgcreate systemvg $diskPartition >/dev/null 2>&1
 	else
-		mke2fs $diskPartition >/dev/null 2>&1
-		if test $? != 0;then
-			systemException \
-				"Failed to create filesystem on: $diskPartition !" \
-			"reboot"
-		fi
+		# .../
+        # There is no need to create a filesystem on the partition
+        # because the image itself contains the filesystem
+        # ----
+		# mke2fs $diskPartition >/dev/null 2>&1
+		# if test $? != 0;then
+		#	systemException \
+		#		"Failed to create filesystem on: $diskPartition !" \
+		#	"reboot"
+		# fi
+		:
 	fi
 }
 partitionCount () {
