- changed the way how the size request of LVM volumes in an oem image   is processed. Before this patch the volumes were created with the   requested size and stored in the image. Thus we store a lot of null   bytes inside the image and also dump those null bytes when running   the code of an oem install image. As the oem image by design expands   itself on first boot according to the target disk and oem image   configuration parameters, it's more clean and also faster to resize   the volumes on first boot and not keep them with their requested   size inside the image (bnc#761993)

diff --git a/system/boot/s390/oemboot/suse-repart b/system/boot/s390/oemboot/suse-repart
--- a/system/boot/s390/oemboot/suse-repart
+++ b/system/boot/s390/oemboot/suse-repart
@@ -396,6 +396,10 @@ function OEMRepartLVM {
 			swapParam=yes
 		fi
 		#======================================
+		# Resize volumes to requested size
+		#--------------------------------------
+		resizeLVMVolumes
+		#======================================
 		# Extend root + optional allFreeVolume
 		#--------------------------------------
 		if [ -z "$OEM_SYSTEMSIZE" ];then
@@ -747,3 +751,31 @@ function disableRepart {
 	DONT_PARTITION=1
 }
 
+#======================================
+# resizeLVMVolumes
+#--------------------------------------
+function resizeLVMVolumes {
+	local variable
+	local volume
+	local content
+	local mode
+	local size
+	for i in $(cat /.profile | grep kiwi_LVM_);do
+		variable=$(echo $i|cut -f1 -d=)
+		volume=$(echo $i| cut -f3 -d_ | cut -f1 -d=)
+		content=$(eval echo \$$variable)
+		mode=$(echo $content | cut -f1 -d:)
+		size=$(echo $content | cut -f2 -d:)
+		Echo "Resizing volume $volume..."
+		if [ $mode = "size" ];then
+			lvextend -L ${size}M /dev/$VGROUP/$volume
+		else
+			lvextend -L +${size}M /dev/$VGROUP/$volume
+		fi
+		if [ $? = 0 ];then
+			resizeFilesystem /dev/$VGROUP/$volume
+		else
+			Echo "Warning: requested size cannot be reached !"
+		fi
+	done
+}
