- update s390 boot code according to generic changes in the x86 boot code

diff --git a/system/boot/s390/oemboot/suse-dump b/system/boot/s390/oemboot/suse-dump
--- a/system/boot/s390/oemboot/suse-dump
+++ b/system/boot/s390/oemboot/suse-dump
@@ -99,11 +99,11 @@ function OEMFindPartitions {
 		local kbsize=$(echo $i | cut -f1 -d:)
 		local mbsize=$((kbsize / 1024))
 		local partid=$(partitionID /dev/$disk $(nd $device))
-		if [ ! "$partid" = "83" ] && [ ! "$partid" = "8e" ] ;then
+		if [ ! "$partid" = "83" ];then
 			continue
 		fi
 		probeFileSystem $device
-		if [ ! -z "$FSTYPE" ] && [ "$FSTYPE" != "unknown" ];then
+		if [ ! -z "$FSTYPE" ] && [ ! "$FSTYPE" = "unknown" ];then
 			continue
 		fi
 		if [ -z "$result" ];then
@@ -127,7 +127,7 @@ function OEMInstall {
 	local dsize=0
 	local index=0
 	local message
-	local prefix=/cdrom
+	local prefix
 	#======================================
 	# Check for install mode indicator file
 	#--------------------------------------
@@ -254,27 +254,21 @@ function OEMInstall {
 	#======================================
 	# Evaluate OEM install file
 	#--------------------------------------
-	field=0
-	imageZipped="uncompressed"
-	IFS=";" ; for n in $IMAGE;do
-	case $field in
-		0) field=1 ;; 
-		1) imageName=$n   ; field=2 ;;
-		2) imageVersion=$n; field=3 ;;
-		3) imageZipped=$n ;
-	esac
-	done
+	imageName=$(echo $IMAGE | cut -f2 -d=)
 	if [ ! -z "$pxe" ];then
 		prefix=/image
-	fi
-	if [ "$imageZipped" = "compressed" ];then
-		imageName="$prefix/$imageName.gz"
-		imageMD5="$imageName.md5"
 	else
-		imageName="$prefix/$imageName"
-		imageMD5="$imageName.md5"
+		prefix=/squashed
+		mkdir -p $prefix
+		if ! mount -o loop /cdrom/$imageName.squashfs $prefix;then
+			systemException \
+				"Failed to mount install image container" \
+			"reboot"
+		fi
 	fi
-	IFS=$IFS_ORIG
+	imageName=$prefix/$imageName
+	imageMD5=$(echo $imageName | sed -e s@.raw@.md5@)
+	OEMRootImage=$imageName
 	#======================================
 	# Search, ask for the install partition
 	#--------------------------------------
@@ -283,6 +277,8 @@ function OEMInstall {
 		# Loop mount disk image file
 		#--------------------------------------
 		reqpart=1
+		info=/tmp/partinfo
+		wmrc=/wmrc
 		loop=$(losetup -s -f $imageName)
 		loop=$(echo $loop | sed -e s@^/dev/@@)
 		if ! kpartx -a /dev/$loop;then
@@ -305,47 +301,110 @@ function OEMInstall {
 				"Installation aborted..." \
 			"reboot"
 		fi
-		partitions=$(OEMFindPartitions $instDisk)
-		if [ ! -z "$partitions" ];then
-			count=0
-			IFS=","
-			for i in $partitions;do
-				count=$((count + 1))
-			done
-			IFS=$IFS_ORIG
-		fi
-		if [ -z "$partitions" ] || [ $count -lt $reqpart ];then
-			if [ -z "$partitions" ];then
-				Echo "No suitable partition(s) for installation found:"
-			else
-				Echo "Not enough partitions for installation found:"
-				Echo "Found $count but required $reqpart"
+		while true;do
+			partitions=$(OEMFindPartitions $instDisk)
+			if [ ! -z "$partitions" ];then
+				count=0
+				IFS=","
+				for i in $partitions;do
+					count=$((count + 1))
+				done
+				IFS=$IFS_ORIG
 			fi
-			Echo "Please prepare your disk first:"
-			echo
-			Echo -b "kiwi requires $reqpart partition(s) of the types below"
-			Echo -b "without any filesystem inside. I recommend to use YaST"
-			Echo -b "to do the re-partitioning. YaST also allows you to shrink"
-			Echo -b "existing partitions without loosing data."
-			echo
-			count=0
-			for i in /dev/mapper/${loop}*;do
-				psize=`partitionSize $i`
-				partid=$(partitionID /dev/$loop $(nd $i))
-				if [ $count = 0 ];then
-					Echo -b "* Root partition requires at least $psize KB"
+			if [ -z "$partitions" ] || [ $count -lt $reqpart ];then
+				#======================================
+				# Print partition user information
+				#--------------------------------------
+				if [ -z "$partitions" ];then
+					echo "No suitable partition(s) for installation found:" \
+						 > $info
+				else
+					echo "Not enough partitions for installation found:" \
+						 > $info
+					echo "Found $count but required $reqpart"      >> $info
 				fi
-				if [ $count = 1 ];then
-					Echo -b "* Boot partition requires at least $psize KB"
+				echo "Please prepare your disk first:"             >> $info
+				echo >> $info
+				echo "kiwi requires $reqpart partition(s) of the"  >> $info
+				echo "types below without any filesystem inside !" >> $info
+				echo >> $info
+				count=0
+				for i in /dev/mapper/${loop}*;do
+					psize=`partitionSize $i`
+					partid=$(partitionID /dev/$loop $(nd $i))
+					partname=Root
+					if [ $reqpart -eq 2 ] && [ $count = 0 ];then
+						partname=Boot
+					fi
+					echo "* $partname partition requires at least $psize KB" \
+						>> $info
+					echo "  Partition Type: 0x$partid" >> $info
+					count=$((count + 1))
+				done
+				#======================================
+				# Mount OEM root image read-write
+				#--------------------------------------
+				OEMRootSystem=/system
+				mkdir -p $OEMRootSystem
+				createSnapshotMap $OEMRootImage
+				if [ ! -e $snapshotMap ];then
+					systemException \
+						"Failed to create CD root snapshot map..." \
+					"reboot"
 				fi
-				Echo -b "  Partition Type: 0x$partid"
-				count=$((count + 1))
-			done
-			echo
-			systemException \
-				"Installation aborted..." \
-			"reboot"
-		fi
+				if ! mount $snapshotMap $OEMRootSystem;then
+					systemException \
+						"Failed to mount OEM root image..." \
+					"reboot"
+				fi
+				#======================================
+				# Check OEM image tool chain
+				#--------------------------------------
+				for i in \
+					usr/sbin/gparted \
+					usr/bin/dialog   \
+					usr/bin/xinit    \
+					usr/bin/xterm    \
+					usr/bin/dialog   \
+					usr/bin/icewm
+				do
+					if [ ! -e $OEMRootSystem/$i ];then
+						systemException \
+							"missing $i in OEM image..." \
+						"reboot"
+					fi
+				done
+				#======================================
+				# Make system devices available
+				#--------------------------------------
+				for i in dev sys proc dev/pts;do
+					mount --bind /$i /system/$i
+				done
+				#======================================
+				# Start gparted for partition setup
+				#--------------------------------------
+				cp $info /system/tmp
+				cp $wmrc /system/tmp
+				chroot /system 	xinit /bin/bash -c '
+					icewm -c /tmp/wmrc &
+					xterm +sb -e dialog --textbox /tmp/partinfo 20 70 &
+					gparted $imageDiskDevice
+				' -- :0 vt7
+				#======================================
+				# Cleanup and recheck
+				#--------------------------------------
+				for i in dev/pts proc sys dev;do
+					umount /system/$i
+				done
+				umount $OEMRootSystem
+				resetSnapshotMap
+				continue
+			fi
+			#======================================
+			# Partition setup fine, proceed
+			#--------------------------------------
+			break
+		done
 		#======================================
 		# Do we have a LVM image...
 		#--------------------------------------
@@ -372,9 +431,9 @@ function OEMInstall {
 			#--------------------------------------
 			for p in /dev/mapper/${loop}*;do
 				if [ $p = /dev/mapper/${loop}p1 ];then
-					select="root"
-				elif [ $p = /dev/mapper/${loop}p2 ];then
 					select="boot"
+				elif [ $p = /dev/mapper/${loop}p2 ];then
+					select="root"
 				fi
 				TEXT_SELECT=$(
 					getText "Select %1 partition for installation:" $select)
@@ -411,20 +470,27 @@ function OEMInstall {
 						else
 							partitions_next=$partitions_next,$pname:$psize
 						fi
+						count=$((count + 1))
 					fi
-					count=$((count + 1))
 				done
 				IFS=$IFS_ORIG
 				partitions=$partitions_next
 				if [ $p = /dev/mapper/${loop}p1 ];then
 					imageDevice=$selectedPart
-					rID=$(nd $selectedPart)
-					instItems[0]=$imageName:$imageDevice
-				elif [ $p = /dev/mapper/${loop}p2 ];then
 					bID=$(nd $selectedPart)
+					instItems[0]=/dev/mapper/${loop}p1:$imageDevice
+				elif [ $p = /dev/mapper/${loop}p2 ];then
+					rID=$(nd $selectedPart)
 					instItems[1]=/dev/mapper/${loop}p2:$selectedPart
 				fi
 			done
+			# /.../
+			# reverse order of instItems because
+			# root partition must be first entry
+			# ----
+			instItems_tmp=${instItems[0]}
+			instItems[0]=${instItems[1]}
+			instItems[1]=$instItems_tmp
 		fi
 		#======================================
 		# Search for a swap space
@@ -448,9 +514,9 @@ function OEMInstall {
 			bID=$rID
 		fi
 		if [ "$haveLVM" = "yes" ];then
-			setupDeviceNames $rID $sID no no $bID no $VGROUP
+			setupDeviceNames $rID $sID no $bID no $VGROUP
 		else
-			setupDeviceNames $rID $sID no no $bID no
+			setupDeviceNames $rID $sID no $bID no
 		fi
 	else
 		instItems[0]=$imageName:$imageDevice
@@ -470,9 +536,6 @@ function OEMInstall {
 		if [ -z "$nombridcheck" ];then
 			mbrD=$instDisk
 			mbrI="cat $imageName"
-			if [ "$imageZipped" = "compressed" ];then
-				mbrI="gzip -cd $imageName"
-			fi
 			mbrM=$(dd if=$mbrD bs=1 count=4 \
 				skip=$((0x1b8))|hexdump -n4 -e '"0x%x"')
 			mbrI=$($mbrI | dd  bs=1 count=4 \
@@ -562,12 +625,14 @@ function OEMInstall {
 		#--------------------------------------
 		if [ -z "$pxe" ];then
 			dump="cat $Source"
-			if test "$imageZipped" = "compressed"; then
-				dump="gzip -cd $Source"
-			fi
 			if [ -x /usr/bin/dcounter ];then
-				progressBaseName=$(basename $Source)
-				TEXT_LOAD=$(getText "Loading %1" $progressBaseName)
+				if [ ! -z "$OEM_PARTITION_INSTALL" ];then
+					progressP=$(echo $Source | cut -f5 -dp)
+					progressBaseName="$(basename $OEMRootImage) [p$progressP]"
+				else
+					progressBaseName=$(basename $Source)
+				fi
+				TEXT_LOAD=$(getText "Loading %1" "$progressBaseName")
 				dump="$dump | dcounter -s $needMByte -l \"$TEXT_LOAD \""
 			fi
 			Echo "Loading $Source [$Target] "
@@ -606,7 +671,7 @@ function OEMInstall {
 		else
 			multicast="disable"
 			Echo "Loading $Source [$Target BS:$imageBlkSize Byte]..."
-			fetchFile $Source $Target $imageZipped $imageServer
+			fetchFile $Source $Target uncompressed $imageServer
 			if test $loadCode != 0 || ! loadOK "$loadStatus";then
 				systemException \
 					"Download of $imageName failed: $loadStatus" \
@@ -631,6 +696,7 @@ function OEMInstall {
 		if [ -x /usr/bin/dcounter ];then
 			test -e /progress || mkfifo /progress
 			TEXT_VERIFY=$(getText "Verifying %1" $imageDevice)
+			echo "$TEXT_VERIFY ( 0% )" > /progress &
 			dump="cat $imageDevice"
 			dump="$dump | dcounter -s $verifyMByte -l \"$TEXT_VERIFY \""
 			errorLogStop
@@ -670,7 +736,10 @@ function OEMInstall {
 	#======================================
 	# Umount CD/DVD USB
 	#--------------------------------------
-	umount /cdrom
+	if [ -z "$pxe" ];then
+		umount /squashed
+		umount /cdrom
+	fi
 	#======================================
 	# Reread partition table
 	#--------------------------------------
