- Added support for multipath devices
  <oem-multipath-scan>true|false</oem-multipath-scan>

  by default the scanning for multipath devices is turned on.
  The code in the initrd looking up multipath devices also
  checks for preconditions like the ability to start the
  multipathd and use the multipath tools. If you don't see
  the multipath devices in the selection list but expect
  this according to the oemconfig setup please refer to the
  kiwi boot log file for further details

diff --git a/system/boot/ix86/oemboot/suse-dump b/system/boot/ix86/oemboot/suse-dump
--- a/system/boot/ix86/oemboot/suse-dump
+++ b/system/boot/ix86/oemboot/suse-dump
@@ -217,11 +217,13 @@ function OEMInstall {
 	# Add optional dmraid device(s)
 	#--------------------------------------
 	if [ -z "$DISABLE_OEM_ATARAID_SCAN" ];then
-		if lookup dmraid &>/dev/null && dmraid -s &>/dev/null;then
-			dmraid -a y
-			udevPending
-			identifyDMRaid
-		fi
+		identifyDMRaid
+	fi
+	#======================================
+	# Add optional multipath device(s)
+	#--------------------------------------
+	if [ -z "$DISABLE_OEM_MULTIPATH_SCAN" ];then
+		identifyMultipath
 	fi
 	#======================================
 	# Run user script
@@ -988,6 +990,73 @@ function identifyDevice {
 }
 
 #======================================
+# identifyMultipath
+#--------------------------------------
+function identifyMultipath {
+	local multipath_config=/etc/multipath.conf
+	local device_disks=$deviceDisks
+	local device_disks_new
+	local disk
+	local wwn
+	#======================================
+	# check the tools
+	#--------------------------------------
+	for tool in multipathd multipath;do
+		if ! lookup $tool &>/dev/null;then
+			Echo "identifyMultipath: $tool not found"
+			return
+		fi
+	done
+	#======================================
+	# lookup multipath configuration
+	#--------------------------------------
+	if [ ! -f $multipath_config ];then
+		Echo "identifyMultipath: no multipath configuration found"
+		return
+	fi
+	#======================================
+	# load multipath dm modules
+	#--------------------------------------
+	if ! modprobe dm-multipath;then
+		Echo "identifyMultipath: can't load dm-multipath"
+		return
+	fi
+	#======================================
+	# start multipath daemon
+	#--------------------------------------
+	if ! multipathd;then
+		Echo "identifyMultipath: failed to start multipathd"
+		return
+	fi
+	#======================================
+	# wait for devices to settle
+	#--------------------------------------
+	udevPending
+	#======================================
+	# strip list of disk devices
+	#--------------------------------------
+	# keep only non multipath devices in the list
+	for disk in $device_disks;do
+		if ! multipath -c $disk &>/dev/null;then
+			device_disks_new="$device_disks_new $disk"
+		fi
+	done
+	#======================================
+	# add multipath devices to the list
+	#--------------------------------------
+	for wwn in $(multipath -l -v1);do
+		disk=/dev/mapper/$wwn
+		if [ -e $disk ];then
+			device_disks_new="$device_disks_new $disk"
+		fi
+	done
+	#======================================
+	# return with new disk list
+	#--------------------------------------
+	deviceDisks=$device_disks_new
+}
+
+#======================================
 # identifyDMRaid
 #--------------------------------------
 function identifyDMRaid {
@@ -1001,6 +1070,28 @@ function identifyDMRaid {
 	local device_clean
 	local device_disks
 	local device_disks_new
+	#======================================
+	# check the tool
+	#--------------------------------------
+	if ! lookup dmraid &>/dev/null;then
+		Echo "identifyDMRaid: dmraid tool not found"
+		return
+	fi
+	#======================================
+	# check for raid disks
+	#--------------------------------------
+	if ! dmraid -s &>/dev/null;then
+		Echo "identifyDMRaid: no raid disks found"
+		return
+	fi
+	#======================================
+	# activate raid disks
+	#--------------------------------------
+	dmraid -a y
+	#======================================
+	# wait for devices to settle
+	#--------------------------------------
+	udevPending
 	#======================================
 	# search raid devices and store them
 	#--------------------------------------
